{
    "pageResult": {
        "count": 1,
        "data": [
            {
                "score": 1,
                "data": {
                    "id": 0,
                    "dataModificacao": null,
                    "produtoSistemaId": null,
                    "cna": null,
                    "csa": null,
                    "codigoReferencia": null,
                    "ean": null,
                    "marca": null,
                    "logoMarca": "",
                    "nomeProduto": null,
                    "informacoesComplementares": "",
                    "dimensoes": null,
                    "imagemReal": "",
                    "imagemIlustrativa": "",
                    "linkExibicaoVideo": null,
                    "linkExibicaoVideoEmbed": "",
                    "exibirVideoParaTodasAsMarcas": false,
                    "imagemExpandida": "",
                    "imagemExpandidaPai": "",
                    "pontoCriticoAtencao": null,
                    "familia": null,
                    "imagensTecnicas": [],
                    "possuiAplicacaoAdaptacao": false,
                    "similares": [],
                    "aplicacoes": [
                        {
                            "id": 7239195,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.0 16V D4D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "71",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/88fc6d05-1135-4a49-8be7-ad3e03e78823.jpg",
                            "ranking": 809
                        },
                        {
                            "id": 7239193,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.0 16V D4D",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "71",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/06eabf7b-a93c-459f-918a-b6c06bbf8845.png",
                            "ranking": null
                        },
                        {
                            "id": 26407683,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G2",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/0bee733a-002c-4e1c-b90d-568f18caaa36.jpg",
                            "ranking": null
                        },
                        {
                            "id": 26408369,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G2",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/0bee733a-002c-4e1c-b90d-568f18caaa36.jpg",
                            "ranking": null
                        },
                        {
                            "id": 7239168,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/0bee733a-002c-4e1c-b90d-568f18caaa36.jpg",
                            "ranking": 430
                        },
                        {
                            "id": 7239178,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/0bee733a-002c-4e1c-b90d-568f18caaa36.jpg",
                            "ranking": 430
                        },
                        {
                            "id": 7239218,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.6 16V K4M",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "110",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/173c4ff1-4c9e-4a95-a10c-ed8cfc3fd94c.jpg",
                            "ranking": 1667
                        },
                        {
                            "id": 7239219,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.6 16V K4M",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2003,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "110",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/18acad8b-6814-4e71-871c-85b40bb5a810.png",
                            "ranking": null
                        },
                        {
                            "id": 7239222,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.6 8V C3L",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2002,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "90",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/2c2c103f-9882-43d2-88e5-96efa6ad61d1.jpg",
                            "ranking": 1820
                        },
                        {
                            "id": 7239223,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.6 8V C3L",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2002,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "90",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/4300518c-0259-4965-96a8-7ccdf05cd941.png",
                            "ranking": null
                        },
                        {
                            "id": 7239220,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.6 8V K7M",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2002,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "90",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/50ebd115-fdd4-4ffc-8a99-14815c2bb82a.jpg",
                            "ranking": 1704
                        },
                        {
                            "id": 7239221,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "RL",
                            "geracao": "G2",
                            "motor": "1.6 8V K7M",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 1999,
                            "fabricacaoFinal": 2002,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "90",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/a8931e94-ecc9-4435-ace0-18327c9f82ee.png",
                            "ranking": null
                        },
                        {
                            "id": 14391962,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2006,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "71",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/95b7024a-f589-454d-8496-502186677720.png",
                            "ranking": 660
                        },
                        {
                            "id": 7239216,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "77",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/f343b119-b5f4-48ce-b534-2286763f7233.png",
                            "ranking": null
                        },
                        {
                            "id": 14390804,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "SEDAN",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "77",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/f9df4152-6d15-45c0-a590-1669ea05e01f.png",
                            "ranking": null
                        },
                        {
                            "id": 14391536,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2006,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "71",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/bad3331f-6059-41fe-b50f-f78e813e56c2.png",
                            "ranking": null
                        },
                        {
                            "id": 14395364,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/43bdf6fb-6e5c-427a-9a69-cbf53cc0100a.png",
                            "ranking": 793
                        },
                        {
                            "id": 7239127,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/43bdf6fb-6e5c-427a-9a69-cbf53cc0100a.png",
                            "ranking": 793
                        },
                        {
                            "id": 14614729,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.6 16V K4M",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "110",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/f89a65b7-eb3d-490b-a706-41b22c8007c9.png",
                            "ranking": 1559
                        },
                        {
                            "id": 14615224,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.6 16V K4M",
                            "carroceria": "HATCHBACK",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2004,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "112",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/39a0125d-ad73-4088-b638-8fe0f91810c4.png",
                            "ranking": 1889
                        },
                        {
                            "id": 14616429,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.6 16V K4M",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2003,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "110",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/99b079cf-c39f-4e48-a789-479cea551e9c.png",
                            "ranking": null
                        },
                        {
                            "id": 14615898,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F1",
                            "motor": "1.6 16V K4M",
                            "carroceria": "SEDAN",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2004,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "112",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/635f5ab9-897f-49f8-b089-b4c35ab59a6f.png",
                            "ranking": null
                        },
                        {
                            "id": 7239214,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE HI-FLEX",
                            "geracao": "G3 F2",
                            "motor": "1.0 16V D4D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2010,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "77",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/10de65b8-25ef-43ed-a323-87d5725cfdf0.png",
                            "ranking": 95
                        },
                        {
                            "id": 26372149,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE HI-FLEX",
                            "geracao": "G3 F2",
                            "motor": "1.0 16V D4D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2011,
                            "fabricacaoFinal": 2012,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "77",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/b08ae6cb-b1ae-49c0-b96f-1b83f4c7b7e4.png",
                            "ranking": null
                        },
                        {
                            "id": 7239224,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE HI-FLEX",
                            "geracao": "G3 F2",
                            "motor": "1.0 16V D4D",
                            "carroceria": "SEDAN",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2010,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "77",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/36158a1b-c1c3-44c2-b4e8-7dda39391606.png",
                            "ranking": null
                        },
                        {
                            "id": 7239145,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE HI-FLEX",
                            "geracao": "G3 F2",
                            "motor": "1.0 16V D4D",
                            "carroceria": "SEDAN",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2011,
                            "fabricacaoFinal": 2012,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "77",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/f9a44f68-b607-44a8-9339-2c31644e67dc.png",
                            "ranking": null
                        },
                        {
                            "id": 7239209,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE",
                            "geracao": "G3 F2",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2008,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/8267f916-e5f3-47e1-a896-770371e86349.png",
                            "ranking": 870
                        },
                        {
                            "id": 7239212,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE",
                            "geracao": "G3 F2",
                            "motor": "1.0 8V D7D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2008,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "58",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/8267f916-e5f3-47e1-a896-770371e86349.png",
                            "ranking": 870
                        },
                        {
                            "id": 7239110,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F2",
                            "motor": "1.6 16V K4M",
                            "carroceria": "HATCHBACK",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2006,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "110",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/7bcadb3d-31cb-44ac-873e-cec0882524ac.png",
                            "ranking": 2888
                        },
                        {
                            "id": 7239213,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F2",
                            "motor": "1.6 16V K4M",
                            "carroceria": "HATCHBACK",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2009,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "112",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/8f5ec210-c615-42d4-87a2-9380429a9917.png",
                            "ranking": 1333
                        },
                        {
                            "id": 14617062,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F2",
                            "motor": "1.6 16V K4M",
                            "carroceria": "SEDAN",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2009,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "112",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/76a88da2-227f-439b-8f16-f10a952709c1.jpg",
                            "ranking": null
                        },
                        {
                            "id": 14617601,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "R-LINE",
                            "geracao": "G3 F2",
                            "motor": "1.6 16V K4M",
                            "carroceria": "SEDAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2005,
                            "fabricacaoFinal": 2006,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "110",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/a3680530-c802-4071-af15-0d2101eb7c88.jpg",
                            "ranking": null
                        },
                        {
                            "id": 7239215,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "CLIO",
                            "versao": "AUTHENTIQUE HI-FLEX",
                            "geracao": "G4",
                            "motor": "1.0 16V D4D",
                            "carroceria": "HATCHBACK",
                            "combustivel": "FLEX",
                            "fabricacaoInicial": 2012,
                            "fabricacaoFinal": 2016,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "80",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/70026320-5977-4579-a6ec-e6657854a58d.png",
                            "ranking": 155
                        },
                        {
                            "id": 7239255,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "FURGAO",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "70",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/61d009b6-12e5-4b6f-9a8f-d80ede06f2c2.png",
                            "ranking": 2991
                        },
                        {
                            "id": 7239247,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "MINIVAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "70",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/59ef385f-171a-4fe4-b051-31776a5beb35.png",
                            "ranking": 2910
                        },
                        {
                            "id": 7239227,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "R-LINE",
                            "geracao": "G1 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "MINIVAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "70",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/59ef385f-171a-4fe4-b051-31776a5beb35.png",
                            "ranking": 2910
                        },
                        {
                            "id": 26345921,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 16V D4D",
                            "carroceria": "PICK-UP CAB. SIMPLES",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "70",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/a8a3fc7c-8083-4bea-944d-6667a6320171.png",
                            "ranking": null
                        },
                        {
                            "id": 7239257,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "FURGAO",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "59",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/855369ad-3769-48b5-87af-19cea3ed9639.png",
                            "ranking": 2380
                        },
                        {
                            "id": 7239259,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "FURGAO",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "59",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/855369ad-3769-48b5-87af-19cea3ed9639.png",
                            "ranking": 2380
                        },
                        {
                            "id": 14461883,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "R-LINE",
                            "geracao": "G1 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "MINIVAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "59",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/296cae6f-3a95-47ed-ad71-fdf2d9ad41b5.png",
                            "ranking": 1711
                        },
                        {
                            "id": 7239256,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "MINIVAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "59",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/296cae6f-3a95-47ed-ad71-fdf2d9ad41b5.png",
                            "ranking": 1711
                        },
                        {
                            "id": 7239243,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "RL",
                            "geracao": "G1 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "MINIVAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "59",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/296cae6f-3a95-47ed-ad71-fdf2d9ad41b5.png",
                            "ranking": 1711
                        },
                        {
                            "id": 7239232,
                            "linha": "Leve",
                            "montadora": "RENAULT",
                            "modelo": "KANGOO",
                            "versao": "R-LINE",
                            "geracao": "G1 F1",
                            "motor": "1.0 8V D7D",
                            "carroceria": "MINIVAN",
                            "combustivel": "GASOLINA",
                            "fabricacaoInicial": 2000,
                            "fabricacaoFinal": 2005,
                            "confiavel": true,
                            "adaptacao": false,
                            "informacoesAdicionais": null,
                            "cilindros": "4",
                            "hp": "59",
                            "imagem": "https://catalogopdtstorage.blob.core.windows.net/imagens-prd/veiculo/296cae6f-3a95-47ed-ad71-fdf2d9ad41b5.png",
                            "ranking": 1711
                        },
                        {