name: Deploy to VPS (Simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          # Navegar para o diretório do projeto
          cd /opt/partexplorer
          
          # Fazer pull das mudanças
          git pull origin main
          
          # Parar containers existentes
          docker-compose down
          
          # Rebuild e subir containers
          docker-compose build --no-cache
          docker-compose up -d
          
          # Verificar status
          docker-compose ps
          
          # Limpar imagens não utilizadas
          docker image prune -f
          
          echo "Deploy completed successfully!" 